server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(mp3|json)$ {
        add_header Cache-Control "public, max-age=31536000";
    }
}